services:
  main:
    build: .
    environment:
      - ENVIRONMENT=local
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - "8000:8000"